[package]
name = "veloren_server_bot"
version = "0.2.0"
authors = ["Songtronix <contact@songtronix.com>"]
edition = "2018"
publish = false

[dependencies]
# Async
tokio = { version = "1.2.0", features = ["macros", "process", "rt-multi-thread", "sync"] }
tokio-stream = { version = "0.1.4", features = ["io-util"] }
futures = "0.3.13"
# Logging
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4.19"
log = "0.4.14"
# Config
config = { version = "0.10.1", features = ["yaml"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_yaml = "0.8.17"
# Error handling
anyhow = "1.0.38"
# Discord
serenity = { version = "0.10.4", features = ["cache", "framework", "standard_framework", "rustls_backend"] }
# Other
linked_hash_set = { version = "0.1.4", features = ["serde"] }
lazy_static = "1.4.0"
