version: "3.5"

services:
  veloren-server-bot:
    build: .
    container_name: veloren-server-bot
    ports:
      - "14004:14004"
      - "14005:14005"
    restart: on-failure:0
    volumes:
      - "./data/veloren:/veloren"
      - "./data/settings:/data"
    environment:
      - BOT_SETTINGS=data/settings.toml
