version: "3.5"

services:
  veloren-server-bot:
    build: .
    container_name: veloren-server-bot
    ports:
      - "14004:14004"
      - "14005:14005"
    restart: on-failure:0
    volumes:
      - "./data/veloren:/veloren"
      - "./data/settings:/data"
      - logs:/data/logs
    environment:
      - BOT_SETTINGS=data/settings.toml
      - BOT_LOGS=data/logs/bot.log
  frontail:
    image: mthenw/frontail
    container_name: frontail
    depends_on: [veloren-server-bot]
    ports:
      - "9001:9001"
    restart: on-failure:0
    volumes:
      - "logs:/logs"
    command: /logs/bot.log

volumes:
  logs:
