# This workflow creates the server image and publishes it.
name: Server Image

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/songtronix/veloren-server-bot
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}},priority=100
            type=ref,event=branch,priority=200
            type=sha,priority=300

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-master-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-master-

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        id: docker_build
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
